"""
backtest.py —— 把模型信号接回 backtesting.py
backtest.py —— Feed model signals back into backtesting.py
=============================================
拿 model.walk_forward 生成的【样本外】概率 P(涨),用概率阈值做交易:
Take the [out-of-sample] probability P(up) generated by model.walk_forward, and trade using a probability threshold:

    P(涨) > buy_th   -> 模型有把握,持有(满仓做多)
    P(up) > buy_th   -> model is confident, hold (fully long)
    P(涨) < sell_th  -> 模型没把握,空仓避险(离场持币)
    P(up) < sell_th  -> model is unsure, go flat to avoid risk (exit and hold cash)

为什么是阈值而不是无脑跟随?
Why a threshold instead of blindly following?
    因为模型的价值往往不是"多赚",而是"该跑的时候跑掉、躲开大回撤"。
    Because the model's value is often not "earning more" but "getting out when you should, avoiding big drawdowns".
    空仓避险 = 把仓位控制(Day 3 学的头号风控)交给模型判断。
    Going flat to avoid risk = handing position control (the top risk-control lesson from Day 3) to the model's judgment.

没有未来函数的保证:
Guarantee of no look-ahead (future function):
    - Proba[t] 只用到第 t 天收盘为止的特征;
    - Proba[t] only uses features up to the close of day t;
    - backtesting.py 默认在【下一根K线的开盘】成交 —— 收盘决策、次日开盘执行,合规。
    - backtesting.py by default fills at [the open of the next bar] —— decide at close, execute at next-day open, compliant.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from backtesting import Backtest, Strategy

from quantmill import config


class MLStrategy(Strategy):
    """基于模型概率 + 阈值的多空(其实是"持有 / 空仓")策略。
    A long/short (really "hold / flat") strategy based on model probability + threshold.
    """
    buy_th = config.BUY_TH   # 概率高于此 -> 买入/持有 | Probability above this -> buy / hold
    sell_th = config.SELL_TH  # 概率低于此 -> 清仓避险 | Probability below this -> close position to avoid risk

    def init(self):
        # Proba 作为额外数据列注入,这里不用预计算什么 | Proba is injected as an extra data column; nothing to precompute here
        pass

    def next(self):
        p = self.data.Proba[-1]      # 当前这天模型给的 P(涨) | The P(up) the model gives for the current day
        if np.isnan(p):
            return
        if p > self.buy_th and not self.position:
            self.buy()                # 满仓做多(size 默认吃满可用现金) | Go fully long (size defaults to using all available cash)
        elif p < self.sell_th and self.position:
            self.position.close()     # 清仓避险 | Close position to avoid risk


def run_ml_backtest(
    feat_df: pd.DataFrame,
    proba: pd.Series,
    cash: float = config.CASH,
    commission: float = config.COMMISSION,   # 0.2% = 手续费 + 滑点(打包)| commission + slippage (bundled)
    buy_th: float = config.BUY_TH,
    sell_th: float = config.SELL_TH,
):
    """
    运行 ML 策略回测。
    Run the ML strategy backtest.

    参数:
    Parameters:
        feat_df    : 含 OHLCV 的完整特征表(features.build_dataset 的第三个返回值)
                     Full feature table containing OHLCV (the third return value of features.build_dataset)
        proba      : walk_forward 生成的样本外 P(涨) 序列(前段为 NaN)
                     Out-of-sample P(up) series generated by walk_forward (the early part is NaN)
        cash       : 初始资金
                     Initial capital
        commission : 单边成本(手续费+滑点)
                     One-way cost (commission + slippage)
        buy_th/sell_th : 买入/清仓的概率阈值
                         Probability thresholds for buying / closing

    返回:
    Returns:
        (bt, stats):backtesting.py 的回测对象与统计结果
        (bt, stats): backtesting.py's backtest object and statistics result
    """
    data = feat_df.copy()
    data["Proba"] = proba
    # 只保留有样本外预测的区间(前面用于最初训练的部分丢掉) | Keep only the range with out-of-sample predictions (drop the earlier part used for the initial training)
    data = data.dropna(subset=["Proba"])
    data = data[["Open", "High", "Low", "Close", "Volume", "Proba"]]

    if len(data) < 30:
        raise ValueError(f"可回测区间太短({len(data)} 行),换更长的日期范围")

    bt = Backtest(data, MLStrategy, cash=cash, commission=commission,
                  trade_on_close=False,    # 次日开盘成交,不偷看当日收盘 | Fill at next-day open, no peeking at the current close
                  finalize_trades=True)    # 回测结束时平掉未平仓,统计更准 | Close open positions when the backtest ends, for more accurate statistics
    stats = bt.run(buy_th=buy_th, sell_th=sell_th)
    return bt, stats


if __name__ == "__main__":
    from quantmill.data import get_ohlcv
    from quantmill.factor import build_dataset
    from quantmill.model import walk_forward

    df = get_ohlcv("AAPL", "us", start="2018-01-01", end="2024-01-01")
    X, y, feat_df = build_dataset(df, horizon=5)
    proba = walk_forward(X, y, n_splits=5)
    bt, stats = run_ml_backtest(feat_df, proba)

    for k in ["Start", "End", "Return [%]", "Buy & Hold Return [%]",
              "Max. Drawdown [%]", "Sharpe Ratio", "# Trades", "Win Rate [%]"]:
        print(f"{k:.<26} {stats[k]}")
